slug: query-governance

title: Query Governance

description: |
  ## Quickstart for Query Governance
  
  This dashboard, being interactive and real-time, will provide a holistic view on the volume of scanned events by queries and sources, thus enabling you to optimize resource utilization and improve query performance.

  This quickstart includes dashboards for the following scanned events charts:
  - General Scanned Events (Query Volume)
  - Volume by Account
  - Volume by Source
  - Volume by API Key
  - Volume by User
  - Volume by Individual Dashboards


summary: |
  Dissect the query volume by source. Identify any dashboards that are generating a large number of queries, possibly indicating a need for optimization.

level: New Relic
icon: logo.png

authors:
  - Carolina Rotstein

keywords:
  - Scanned Events
  - NRDB
  - Query
  - Governance

documentation:  
  - name: New Relic NRDB
    url: https://docs.newrelic.com/docs/data-apis/get-started/nrdb-horsepower-under-hood/
    description: Learn more about how NRDB returns results for queries of all sizes astonishingly fast. To do this, we use parallel processing at massive scale.


dataSourceIds:
  - scanned-events-query-governance

dashboards:
  - scanned-events-query-governance