id: apache-zookeeper
displayName: Apache ZooKeeper
description: |
  Unlock the power of Apache ZooKeeper monitoring with the seamless integration of New Relic infrastructure.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/zookeeper-monitoring-integration/
icon: logo.png
