id: amazon-vpc-lattice
displayName: Amazon VPC Lattice
description: Monitor Amazon VPC Lattice by sending Access logs or CloudWatch metrics to New Relic
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-vpc-lattice-monitoring-integration/
icon: logo.jpeg
