id: 28967bd0-fe5a-4482-9f1f-49ef042db9f1

# Name of the quickstart
slug: mevn-stack

# Title of the quickstart
title: MEVN Stack

summary: |
  Monitor your apps using New Relic MEVN integration with Vue, MongoDB and NodeJS agents for browser, database and application monitoring.

# Description of the quickstart
description: |
  ## Comprehensive MEVN Stack Monitoring System
  MEVN stack is a popular Javascript software stack that has become very popular in recent times to build powerful web applications. It comprises four essential components, namely MongoDB, ExpressJS, Vue, and NodeJS. These components integrate seamlessly and logically, making it easy to create web applications using this powerful technology stack. Each of these four components has a crucial role to play in the development of web applications.

  ## What’s included in the MEVN quickstart?
  Install this quickstart to setup preconfigured observability solutions:
  - MongoDB metrics such as active connections, database details, and usage time
  - For ExpressJS and NodeJS, there are a variety of metrics available, including web transactions, the top ten errors, and memory usage
  - Vue metrics include viewed urls, page views by city, AJAX requests, etc. In addition, you may create your own chart based on the metrics collected
  - A number of high-value alerts are available including the average number of connections created, the FCP score and memory usage

# The logo of the quickstart
icon: logo.png

# Support level
level: New Relic

# Authors of the quickstart
authors:
  - New Relic
  - Ramana Reddy

keywords:
  - MEVN
  - MongoDB
  - ExpressJS
  - Vue
  - NodeJS
  - Fullstack application monitoring
  - browser agent
  - language agent
  - featured

dashboards:
  - mexn
alertPolicies:
  - mexn
documentation:
  - name: MEVN Stack installation documentation
    description: |
      Integrate your MEVN app and get your data into New Relic.
    url: >-
      https://docs.newrelic.com/docs/browser/browser-integrations/mexn-integration/
dataSourceIds:
  - node-js
  - new-relic-browser
  - mongodb
