id: active-directory
displayName: Active Directory monitoring
description: |
  Quickly monitor your Active Directory environment for a comprehensive view of health and availability.
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/active-directory-integration/
icon: logo.svg
