id: 65bd74f6-cfb7-4fb9-83a3-38cea143d839
slug: mux-video
description: |
  ## What is Mux?

  Mux is video infrastructure for the internet. With just a few lines of code, companies can get real-time analytics at world-leading scale, and understand their streaming data, monitor user engagement, and improve the quality of experience for viewers. Mux is trusted by today’s largest broadcasters and leaders in streaming video to reach their goals with actionable insights. And together with Mux Video, developers can also build video into their products quickly, reliably, and at global scale.
  Learn more at [mux.com/data](https://mux.com/data)


  ### Get started!

  The Mux - New Relic integration utilizes Amazon Kinesis Firehose to get data into New Relic. 

  Check out the [documentation](https://docs.newrelic.com/docs/logs/forward-logs/mux-video-streaming-firehose/) to learn more about setting up New Relic monitoring for of data from Mux.
summary: |
  Mux is video infrastructure that makes it easy for development teams to get actionable data at industry-leading scale, and build video into their products quickly and reliably.
icon: logo.svg
level: New Relic
authors:
  - New Relic (Joseph Counts)
title: Mux Video Analytics (via Amazon Firehose)
dataSourceIds:
  - mux-video
dashboards:
  - mux-video-analytics
documentation:
  - name: Mux installation docs
    description: Send Mux logs to New Relic using Amazon Firehose
    url: https://docs.newrelic.com/docs/logs/forward-logs/mux-video-streaming-firehose/
keywords:
  - mux
  - video
  - streaming
  - newrelic partner
