id: blazemeter
displayName: BlazeMeter
description: |
  The BlazeMeter New Relic integration allows you to collect metrics from API monitoring tests and transform them into actionable insights about your applications inside New Relic.
icon: logo.png
install:
  primary:
    link:
      url: https://guide.blazemeter.com/hc/en-us/articles/13326704491153-New-Relic-Insights-Integration
keywords:
  - blazemeter
  - api
  - performance
  - load
  - stress
  - functional
  - testing
categoryTerms:
  - open source monitoring