id: 47ef32ba-fd2c-4ff1-9866-0c5847d5c6ca
slug: azure-immersive-reader
description: |-
  ## What is Azure Immersive Reader?
  
   Azure Immersive Reader is part of Azure Applied AI Services and is an inclusively designed tool that implements proven techniques to improve reading comprehension for new readers, language learners and people with learning differences such as dyslexia. 
  
   ### New Relic Azure Immersive Reader quickstart features
  
   A standard dashboard that tracks key indicators like total calls, successful calls, processed characters and total errors. It runs custom queries and visualizes the data immediately.
  
   ### Why monitor Azure Immersive Reader with New Relic?
  
   [New Relic Azure Immersive Reader](https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-cognitive-services-monitoring-integration/) monitoring quickstart empowers you to track the performance of Azure Immersive Reader via different metrics including total calls, successful calls, processed characters and total errors.
  
   Our integration features a standard dashboard that provides interactive visualizations to explore your data, understand context and get valuable insights.
  
   Start ingesting your Azure data today and get immediate access to our visualization dashboards so you can optimize your Azure service.
summary: |-
  Monitoring Azure Immersive Reader is critical to track the performance through key metrics. Download New Relic Azure Immersive Reader monitoring quickstart to get a pre-built dashboard tailored to monitor your Azure Immersive Reader.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - New Relic Partner
title: Azure Immersive Reader
documentation:
  - name: Azure Immersive Reader installation docs.
    description: |
      Monitor Azure Immersive Reader by connecting Azure to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-cognitive-services-monitoring-integration/
keywords:
  - azure
  - cognitive services
  - immersive reader
  - product partnerships
dashboards:
  - azure-immersive-reader
dataSourceIds:
  - azure-monitor