id: 20964ca2-a00c-4f70-9d25-59ce5208f845
slug: azure-language-service
description: |-
  ## What is Azure Language Service?
  
   Azure Cognitive Service for Language is a cloud-based service that provides Natural Language Processing (NLP) features for understanding and analyzing text. Use this service to help build intelligent applications using the web-based Language Studio, REST APIs and client libraries.
  
   ### New Relic Azure Language Service quickstart features
  
   A standard dashboard that tracks key indicators like total calls, successful calls, success rate, processed text records, processed health text records and total errors. It runs custom queries and visualizes the data immediately.
  
   ### Why monitor Azure Language Service with New Relic?
  
   [New Relic Azure Language Service](https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-cognitive-services-monitoring-integration/) monitoring quickstart empowers you to track the performance of Azure Language Service via different metrics including total calls, successful calls, processed text records, processed health text records and total errors.
  
    Our integration features a standard dashboard that provides interactive visualizations to explore your data, understand context and get valuable insights.
  
   Start ingesting your Azure data today and get immediate access to our visualization dashboards so you can optimize your Azure service.
summary: |-
  Monitoring Azure Language Service is critical to track the performance through key metrics. Download New Relic Azure Language Service monitoring quickstart to get a pre-built dashboard tailored to monitor your Azure Language Service.
icon: logo.png
level: New Relic
authors:
  - New Relic
  - New Relic Partner
title: Azure Language Service
documentation:
  - name: Azure Language Service installation docs.
    description: |
      Monitor Azure Language Service by connecting Azure to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/azure-cognitive-services-monitoring-integration/
keywords:
  - azure
  - cognitive services
  - language
  - product partnerships
dashboards:
  - azure-language-service
dataSourceIds:
  - azure-monitor