id: 7ed6c23d-b8ee-4d2e-b983-f552c7820960
slug: amazon-sagemaker
description: |-
  ## What is Amazon Sagemaker?
  Amazon SageMaker is a fully managed machine learning service. With SageMaker, data scientists and developers can quickly and easily build and train machine learning models, and then directly deploy them into a production-ready hosted environment.
  ### Get started!
  Start monitoring Amazon Sagemaker by connecting Amazon Web Services (AWS) to New Relic! Take a look at our documentation for information on how to set up this integration.
  ### More info
  Check out the [documentation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-sagemaker-monitoring-integration/) to learn more about New Relic monitoring for Amazon Sagemaker.
summary: |-
  Monitor Amazon Sagemaker by connecting AWS to New Relic
icon: logo.png
level: New Relic
authors:
  - New Relic
title: Amazon Sagemaker
documentation:
  - name: Amazon Sagemaker installation docs
    description: |
      Monitor Amazon Sagemaker by connecting AWS to New Relic.
    url: >-
      https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/amazon-sagemaker-monitoring-integration/
keywords:
  - aws
  - amazon web services
  - Sagemaker
alertPolicies:
  - amazon-sagemaker
dashboards:
  - amazon-sagemaker
dataSourceIds:
  - amazon-cloudwatch-metric-streams