id: scanned-events-query-governance
displayName: Scanned Events Query Governance
description: |
  ## Quickstart for Query Governance
  
  This dashboard, being interactive and real-time, will provide a holistic view on the volume of scanned events by queries and sources, thus enabling you to optimize resource utilization and improve query performance.

  This quickstart includes dashboards for the following scanned events charts:
  - General Scanned Events (Query Volume)
  - Volume by Account
  - Volume by Source
  - Volume by API Key
  - Volume by User
  - Volume by Individual Dashboards
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/data-apis/get-started/nrdb-horsepower-under-hood/
icon: logo.png

keywords:
  - query
  - governance
  - scanned
