id: sonarqube
displayName: SonarQube
description: |
  Identify and optimize SonarQube performance with New Relic SonarQube monitoring.
icon: logo.png
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/sonarqube-monitoring-integration/
keywords:
  - sonarqube
