id: aws-transcribe
displayName: AWS Transcribe
description: Monitor AWS Transcribe by sending metrics to New Relic
install:
  primary:
    link:
      url: https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-transcribe-monitoring-integration/
icon: logo.png